version: '3'

services:
  django:
    container_name: django
    build:
      dockerfile: ./build/python/Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: supersecretpassword
    depends_on:
      - db
    volumes:
    - ./:/app

  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
