# Generated by Django 4.0.4 on 2022-05-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='short_link.datemodel')),
                ('link_id', models.CharField(blank=True, default='dnUpX', max_length=120, null=True, unique=True)),
                ('main_url', models.URLField()),
            ],
            bases=('short_link.datemodel',),
        ),
        migrations.CreateModel(
            name='LinkStats',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='short_link.datemodel')),
                ('ip', models.CharField(max_length=120)),
                ('user_agent', models.CharField(max_length=120)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_link.links')),
            ],
            bases=('short_link.datemodel',),
        ),
    ]
